"""renew models

Revision ID: 029737bd7c23
Revises: 
Create Date: 2025-04-22 23:20:58.457517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '029737bd7c23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Uuid(), server_default='01458b4c-ce30-4a0b-b85a-33f944b5ddcb', nullable=False),
    sa.Column('acuity_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), server_default='60', nullable=False),
    sa.Column('acuity_created_at', sa.DateTime(), nullable=False),
    sa.Column('acuity_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=True),
    sa.Column('created_at_here', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified_here', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Uuid(), server_default='24177d39-8c43-4c8a-9044-525e1934fdfe', nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('dump', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), server_default='917e2fa7-7dbd-4c18-b70d-52051bc384e5', nullable=False),
    sa.Column('action', sa.Enum('schedule', 'reschedule_incoming', 'reschedule_same_day', 'reschedule_outgoing', 'cancel', name='eventaction'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('old_time', sa.DateTime(), nullable=True),
    sa.Column('new_time', sa.DateTime(), nullable=True),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('snapshots')
    op.drop_table('appointments')
    # ### end Alembic commands ###
